[build]
  command = "cd exampleSite && hugo --gc --minify -D -b https://Blowfish.page"
  publish = "exampleSite/public"

[build.environment]
HUGO_VERSION = "0.147.0"
HUGO_THEMESDIR = "../.."
HUGO_THEME = "repo"
