languageCode = "ja"
languageName = "日本語"
weight = 3
title = "Blowfish"

[params]
  displayName = "日本語"
  rtl = false
  dateFormat = "2006-01-02"
  logo = "/img/logo_transparent.png"
  description = "強力で、軽量な Hugo のテーマです。"

  [params.author]
    name = "Blowfish"
    email = "nuno@n9o.xyz"
    image = "/img/author_logo.png"
    headline = "強力で、軽量な Hugo のテーマです。"
    bio = "強力で、軽量な Hugo のテーマです。"
    links = [
      { x-twitter = "https://twitter.com/burufugu" },
      { github = "https://github.com/nunocoracao/blowfish" },
    ]
