languageCode = "zh-CN"
languageName = "简体中文"
weight = 4
title = "Blowfish"

[params]
  displayName = "简体中文"
  rtl = false
  dateFormat = "2006-01-02"
  logo = "/img/logo_transparent.png"
  description = "一个强大、轻量级的 Hugo 主题。"

  [params.author]
    name = "Blowfish"
    image = "/img/author_logo.png"
    headline = "一个强大、轻量级的 Hugo 主题。"
    bio = "一个强大、轻量级的 Hugo 主题。"
    links = [
      { x-twitter = "https://twitter.com/burufugu" },
      { github = "https://github.com/nunocoracao/blowfish" },
    ]
