name: Blowfish Docs Deploy

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  REPO_NAME: blowfish-refined

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Hugo setup
        uses: peaceiris/actions-hugo@v2.6.0
        with:
          hugo-version: 0.147.5
          extended: true
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          # Do not specify version if field "packageManager" exists in package.json
          version: 10
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "23.10.0"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Build with Hugo
        env:
          HUGO_THEME: ${{ env.REPO_NAME }}
        run: |
          hugo --minify \
            --themesDir ../.. \
            --source exampleSite \
            --baseURL https://ZhenShuo2021.github.io/${{ env.REPO_NAME }}/ \
            --destination ./public

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./exampleSite/public

  deploy:
    environment:
      name: github-pages
      url: https://ZhenShuo2021.github.io/${{ env.REPO_NAME }}/
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
